version: '3.8'

services:
  php:
    image: php:8.2-apache
    ports:
      - target: 80
        published: 8000
        protocol: tcp
    networks:
      - file_rouge

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: demo
      MYSQL_USER: test
      MYSQL_PASSWORD: pass
    ports:
      - target: 3306
        published: 3307
        protocol: tcp
    networks:
      - file_rouge

  phpma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: pass
      UPLOAD_LIMIT: 20M
    ports:
      - target: 80
        published: 8899
        protocol: tcp
    networks:
      - file_rouge

networks:
  file_rouge:
    external: true
